services:
  dialogue:
    command: --debug --host pi-master --port 1883 --site-id floor1 --site-id pi-voice
      --site-id mobile --site-id office --session-timeout 30 --sound wake /usr/lib/rhasspy/etc/wav/2.wav
      --sound error /usr/lib/rhasspy/etc/wav/beep_error.wav --volume 0.5 --say-chars-per-second
      33 --sound-suffix .wav --sound-suffix .mp3 --sound-suffix .ogg --sound-suffix
      .flac
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-dialogue-hermes
    tty: true
  microphone:
    command: --sample-rate 16000 --sample-width 2 --channels 1 --debug --host pi-master
      --port 1883 --site-id floor1 --device-index 1 --frames-per-buffer 1024
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-microphone-pyaudio-hermes
    tty: true
  speakers:
    command: --play-command 'aplay -q -t wav -D default:CARD=USB' --list-command 'aplay
      -L' --volume 1 --debug --host pi-master --port 1883 --site-id floor1
    depends_on:
    - mqtt
    devices:
    - /dev/snd
    image: rhasspy/rhasspy-speakers-cli-hermes
    tty: true
  speech_to_text:
    command: --asr-command /home/pi/.config/rhasspy/profiles/pl/whisper.sh --debug
      --host pi-master --port 1883 --site-id floor1 --site-id pi-voice --site-id mobile
      --site-id office
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-remote-http-hermes
    tty: true
    volumes:
    - /profiles:/profiles
  text_to_speech:
    command: --credentials-json /home/pi/.config/rhasspy/profiles/pl/tts/googlewavenet/credentials.json
      --cache-dir /home/pi/.config/rhasspy/profiles/pl/tts/googlewavenet/cache --voice
      pl-PL-Wavenet-E --sample-rate 22050 --volume 1 --debug --host pi-master --port
      1883 --site-id floor1 --site-id office --site-id mobile
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-tts-wavenet-hermes
    tty: true
  wake:
    command: --keyword '/profiles/pl/raven/Ayla Jabbra' enabled=True --keyword '/profiles/pl/raven/Ayla
      Jabbra Magda' enabled=True --probability-threshold 0.49 --minimum-matches 1
      --vad-sensitivity 1 --debug --host pi-master --port 1883 --site-id floor1 --site-id
      office --site-id mobile
    depends_on:
    - mqtt
    image: rhasspy/rhasspy-wake-raven-hermes
    tty: true
    volumes:
    - /profiles:/profiles
version: '2'
